

 function output_txt = displaydatacursor(~,evt)      
 
 
    evt_fields=fieldnames(evt);
    rel_field='';

    for i=1:length(evt_fields)
       if strcmpi(evt_fields{i},'target') 
            rel_field=evt_fields{i};
       end
    end
    if isempty(rel_field)
        error('The variable evt does not have the field target')
    end
    userdata=get(evt.(rel_field),'userdata');  
        
     pos = get(evt,'Position');

     if isempty(userdata)
       output_txt = {['X: ',num2str(pos(1),4)],...
                     ['Y: ',num2str(pos(2),4)]};

        % If there is a Z-coordinate in the position, display it as well
        if length(pos) > 2
            output_txt{end+1} = ['Z: ',num2str(pos(3),4)];
        end
        return        
     end
     
     
     
     mfile=userdata{1};
     switch mfile         
         case 'plot_multichunk_results'
             if iscell(userdata) && length(userdata)==5
                output_txt={...
                    ['bird_id: ' userdata{2}]...
                    ['syll_label: ' userdata{3}]...
                    ['templ ind: ' num2str(userdata{4})]...
                    ['no instances: ' num2str(userdata{5})]...
                    ['X: ',num2str(pos(1),4)],...
                    ['Y: ',num2str(pos(2),4)]...
                    };    
             elseif iscell(userdata) && length(userdata)==4
                  output_txt={...
                    ['bird_id: ' userdata{2}]...
                    ['syll_label: ' userdata{3}]...
                    ['templ ind/syll serial #: ' num2str(userdata{4})]... 
                    ['X: ',num2str(pos(1),4)],...
                    ['Y: ',num2str(pos(2),4)]...
                    };   

%              elseif iscell(userdata) && length(userdata)==3
%               output_txt={...
%                 ['bird_id: ' userdata{2}]...
%                 ['syll_label: ' userdata{3}]...   
%                 ['X: ',num2str(pos(1),4)],...
%                 ['Y: ',num2str(pos(2),4)]...
%                 };       
             else
                 error('Userdata is not as expected')
             end
         case 'select_screening_thresholds'
             if isstruct(userdata{2})
                 flds=fieldnames(userdata{2});
                 output_txt='';
                 for i=1:length(flds)
                     if strcmpi(flds{i}(1:3),'ftr')
                        curr_txt=sprintf('%s = %.3e\n',flds{i},userdata{2}.(flds{i}));
                        output_txt=[output_txt,curr_txt];
                     end
                     
                 end                 
             else
                 error('Userdata is not as expected')
             end
             
         case 'slice_performance_training_set_fig_4'
             
             if iscell(userdata) && length(userdata)==4
                  output_txt={...
                    ['bird_id: ' userdata{2}]...
                    ['syll_label: ' userdata{3}]...
                    ['slice #: ' num2str(userdata{4})]... 
                    ['X: ',num2str(pos(1),4)],...
                    ['Y: ',num2str(pos(2),4)]...
                    };   

             else
                 error('Userdata is not as expected')
             end
             
         case 'normalized_performance_fig_5'    
             if iscell(userdata) && length(userdata)==5
                output_txt={...
                    ['bird_id: ' userdata{2}]...
                    ['syll_label: ' userdata{3}]...
                    ['templ ind: ' num2str(userdata{4})]...
                    ['no instances: ' num2str(userdata{5})]...
                    ['X: ',num2str(pos(1),4)],...
                    ['Y: ',num2str(pos(2),4)]...
                    };    
             elseif iscell(userdata) && length(userdata)==4
                  output_txt={...
                    ['bird_id: ' userdata{2}]...
                    ['syll_label: ' userdata{3}]...
                    ['templ ind/syll serial #: ' num2str(userdata{4})]... 
                    ['X: ',num2str(pos(1),4)],...
                    ['Y: ',num2str(pos(2),4)]...
                    };   

     
             else
                 error('Userdata is not as expected')
             end
             
         case 'custom_datatip_demo'
             if iscell(userdata) && length(userdata)==2
                 output_txt={...
                    ['message: ' userdata{2}]...                    
                    };   
             else
                 error('Userdata is not as expected')
             end
             
         case 'plot_motifseq'
             if iscell(userdata) && length(userdata)==2
                 output_txt={...
                    ['file: ' userdata{2}]...                    
                    };   
             else
                 error('Userdata is not as expected')
             end
             
         case 'compare_interveal_length_distributions_from_lbl'
             if iscell(userdata) && length(userdata)==3
                output_txt={...
                    ['seq: ' userdata{2}]...
                    ['interval ind: ' num2str(userdata{3})]...    
                    ['X: ',num2str(pos(1),4)],...
                    ['Y: ',num2str(pos(2),4)]...
                    };    
             else
                 error('Userdata is not as expected')
             end
             
              case 'plot_duration_dists'
             if iscell(userdata) && length(userdata)==2
                output_txt={...
                    ['cat: ' userdata{2}]...                       
                    ['X: ',num2str(pos(1),4)],...
                    ['Y: ',num2str(pos(2),4)]...
                    };    
             else
                 error('Userdata is not as expected')
             end
             
         case 'fig_7_final_optimized_targeting_v2'
             if iscell(userdata) && length(userdata)==5
                output_txt={...
                    ['bird: ' userdata{2}]...
                    ['syll: ' userdata{3}]... 
                    ['pre best inds: ' num2str(userdata{4}(1)) ',' num2str(userdata{4}(2)) ',' num2str(userdata{4}(3))]...
                    ['post best inds: ' num2str(userdata{5}(1)) ',' num2str(userdata{5}(2)) ',' num2str(userdata{5}(3))]...
                    ['slice #, detect crit,thr level']...
                    ['X: ',num2str(pos(1),4)],...
                    ['Y: ',num2str(pos(2),4)]...
                    };    
             else
                 error('Userdata is not as expected')
             end
             
             
         otherwise
             warning('Custom data tip has not been defined for the originating function of this figure')             
     end

